apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: default #!!!!!!!!!!!
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  accounts.artsiom: apiKey, login
  accounts.artsiom.enabled: "true"
  accounts.image-updater: apiKey, login
  accounts.image-updater.enabled: "true"